# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import argos_pb2 as argos__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in argos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArgosServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateStudent = channel.unary_unary(
                '/argos.ArgosService/CreateStudent',
                request_serializer=argos__pb2.CreateStudentRequest.SerializeToString,
                response_deserializer=argos__pb2.CreateStudentResponse.FromString,
                _registered_method=True)
        self.GetStudent = channel.unary_unary(
                '/argos.ArgosService/GetStudent',
                request_serializer=argos__pb2.GetStudentRequest.SerializeToString,
                response_deserializer=argos__pb2.GetStudentResponse.FromString,
                _registered_method=True)
        self.EnrollStudent = channel.unary_unary(
                '/argos.ArgosService/EnrollStudent',
                request_serializer=argos__pb2.EnrollStudentRequest.SerializeToString,
                response_deserializer=argos__pb2.EnrollStudentResponse.FromString,
                _registered_method=True)
        self.GetEnrollments = channel.unary_unary(
                '/argos.ArgosService/GetEnrollments',
                request_serializer=argos__pb2.GetEnrollmentsRequest.SerializeToString,
                response_deserializer=argos__pb2.GetEnrollmentsResponse.FromString,
                _registered_method=True)
        self.CreateCourse = channel.unary_unary(
                '/argos.ArgosService/CreateCourse',
                request_serializer=argos__pb2.CreateCourseRequest.SerializeToString,
                response_deserializer=argos__pb2.CreateCourseResponse.FromString,
                _registered_method=True)
        self.CreateSection = channel.unary_unary(
                '/argos.ArgosService/CreateSection',
                request_serializer=argos__pb2.CreateSectionRequest.SerializeToString,
                response_deserializer=argos__pb2.CreateSectionResponse.FromString,
                _registered_method=True)
        self.ScheduleSection = channel.unary_unary(
                '/argos.ArgosService/ScheduleSection',
                request_serializer=argos__pb2.ScheduleSectionRequest.SerializeToString,
                response_deserializer=argos__pb2.ScheduleSectionResponse.FromString,
                _registered_method=True)
        self.GetSchedule = channel.unary_unary(
                '/argos.ArgosService/GetSchedule',
                request_serializer=argos__pb2.GetScheduleRequest.SerializeToString,
                response_deserializer=argos__pb2.GetScheduleResponse.FromString,
                _registered_method=True)
        self.GetMLPrediction = channel.unary_unary(
                '/argos.ArgosService/GetMLPrediction',
                request_serializer=argos__pb2.MLPredictionRequest.SerializeToString,
                response_deserializer=argos__pb2.MLPredictionResponse.FromString,
                _registered_method=True)
        self.GetStatistics = channel.unary_unary(
                '/argos.ArgosService/GetStatistics',
                request_serializer=argos__pb2.GetStatisticsRequest.SerializeToString,
                response_deserializer=argos__pb2.GetStatisticsResponse.FromString,
                _registered_method=True)


class ArgosServiceServicer(object):
    """Service definition
    """

    def CreateStudent(self, request, context):
        """Student operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrollStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnrollments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCourse(self, request, context):
        """Course operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScheduleSection(self, request, context):
        """Scheduling operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMLPrediction(self, request, context):
        """ML operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatistics(self, request, context):
        """Statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArgosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStudent,
                    request_deserializer=argos__pb2.CreateStudentRequest.FromString,
                    response_serializer=argos__pb2.CreateStudentResponse.SerializeToString,
            ),
            'GetStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudent,
                    request_deserializer=argos__pb2.GetStudentRequest.FromString,
                    response_serializer=argos__pb2.GetStudentResponse.SerializeToString,
            ),
            'EnrollStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollStudent,
                    request_deserializer=argos__pb2.EnrollStudentRequest.FromString,
                    response_serializer=argos__pb2.EnrollStudentResponse.SerializeToString,
            ),
            'GetEnrollments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnrollments,
                    request_deserializer=argos__pb2.GetEnrollmentsRequest.FromString,
                    response_serializer=argos__pb2.GetEnrollmentsResponse.SerializeToString,
            ),
            'CreateCourse': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCourse,
                    request_deserializer=argos__pb2.CreateCourseRequest.FromString,
                    response_serializer=argos__pb2.CreateCourseResponse.SerializeToString,
            ),
            'CreateSection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSection,
                    request_deserializer=argos__pb2.CreateSectionRequest.FromString,
                    response_serializer=argos__pb2.CreateSectionResponse.SerializeToString,
            ),
            'ScheduleSection': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleSection,
                    request_deserializer=argos__pb2.ScheduleSectionRequest.FromString,
                    response_serializer=argos__pb2.ScheduleSectionResponse.SerializeToString,
            ),
            'GetSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedule,
                    request_deserializer=argos__pb2.GetScheduleRequest.FromString,
                    response_serializer=argos__pb2.GetScheduleResponse.SerializeToString,
            ),
            'GetMLPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMLPrediction,
                    request_deserializer=argos__pb2.MLPredictionRequest.FromString,
                    response_serializer=argos__pb2.MLPredictionResponse.SerializeToString,
            ),
            'GetStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatistics,
                    request_deserializer=argos__pb2.GetStatisticsRequest.FromString,
                    response_serializer=argos__pb2.GetStatisticsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'argos.ArgosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('argos.ArgosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArgosService(object):
    """Service definition
    """

    @staticmethod
    def CreateStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.ArgosService/CreateStudent',
            argos__pb2.CreateStudentRequest.SerializeToString,
            argos__pb2.CreateStudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.ArgosService/GetStudent',
            argos__pb2.GetStudentRequest.SerializeToString,
            argos__pb2.GetStudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrollStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.ArgosService/EnrollStudent',
            argos__pb2.EnrollStudentRequest.SerializeToString,
            argos__pb2.EnrollStudentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnrollments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.ArgosService/GetEnrollments',
            argos__pb2.GetEnrollmentsRequest.SerializeToString,
            argos__pb2.GetEnrollmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCourse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.ArgosService/CreateCourse',
            argos__pb2.CreateCourseRequest.SerializeToString,
            argos__pb2.CreateCourseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.ArgosService/CreateSection',
            argos__pb2.CreateSectionRequest.SerializeToString,
            argos__pb2.CreateSectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScheduleSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.ArgosService/ScheduleSection',
            argos__pb2.ScheduleSectionRequest.SerializeToString,
            argos__pb2.ScheduleSectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.ArgosService/GetSchedule',
            argos__pb2.GetScheduleRequest.SerializeToString,
            argos__pb2.GetScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMLPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.ArgosService/GetMLPrediction',
            argos__pb2.MLPredictionRequest.SerializeToString,
            argos__pb2.MLPredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/argos.ArgosService/GetStatistics',
            argos__pb2.GetStatisticsRequest.SerializeToString,
            argos__pb2.GetStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
